### ISSUE TITLE
运行 nexttrace https://api.leo.moe/ 时报错

### ISSUE THREAD

**Issue by bobsam** [sjlleo/nexttrace#100]
## 你正在使用哪个版本的 nexttrace？

系统：MacOS 10.15.7 
版本：NextTrace v1.1.3

## 你看到的异常现象是什么？

在运行 `nexttrace https://api.leo.moe/` 时，报了一个错误：

```sh
NextTrace v1.1.3
Please Choose the IP You Want To TraceRoute
0. 104.26.8.231
1. 104.19.28.108
2. 104.26.9.231
3. 104.19.29.108
4. 2606:4700:3030::ac43:cd76
5. 2606:4700:3030::6815:34ee
Your Option: 2
[NextTrace API] prefered API IP - 104.19.29.108 - 11.59ms
IP Geo Data Provider: LeoMoeAPI
traceroute to 104.26.9.231 (api.leo.moe), 30 hops max, 32 byte packets
2023/04/18 14:34:49 listen ip4:1 : socket: operation not permitted
```

## 你期待看到的正常表现是怎样的？

期待运行结果与ReadMe上写得一致。

## 请附上你的命令

```sh
nexttrace https://api.leo.moe/
```

## 请附上出错时软件输出的错误信息

```sh
2023/04/18 14:34:49 listen ip4:1 : socket: operation not permitted
```

**Comment by tsosunchia** [comment]
这不是BUG

macOS是这样的

有以下三种方法：

- 请命令前加sudo 运行

- 切换为root用户运行

- 参考这个链接https://github.com/sjlleo/nexttrace/issues/93#issuecomment-1493216204

**Comment by bobsam** [comment]
> 这不是BUG
> 
> macOS是这样的
> 
> 有以下三种方法：
> 
> * 请命令前加sudo 运行
> * 切换为root用户运行
> * 参考这个链接[使用sudo执行只能解析出IPv6地址 #93 (comment)](https://github.com/sjlleo/nexttrace/issues/93#issuecomment-1493216204)

是的，刚刚已经找到了解决方案了，已经运行成功了。谢谢回答~~
