### ISSUE TITLE
为什么需要root权限

### ISSUE THREAD

**Issue by pdiosq** [sjlleo/nexttrace#101]
我不是很想给这类软件root权限

**Comment by tsosunchia** [comment]
> 我不是很想给这类软件root权限

参看：https://github.com/sjlleo/nexttrace/issues/100#issuecomment-1512535598

**Comment by pdiosq** [comment]
我是linux用户 但是这类软件不应该是什么权限都不要的吗 为什么要赋权？

**Comment by pdiosq** [comment]
traceroute不用

**Comment by tsosunchia** [comment]
> traceroute不用

- 那你就去用traceroute吧🤗🤗🤗

- setcap来避免使用sudo运行

为什么需要？我刚才也说了之前的issue里有说明，自行查阅。

**Comment by isyekong** [comment]
https://github.com/sjlleo/nexttrace/blob/abc1ecd035d5a98c721af10aeff31d01b299483a/cmd/cmd.go#L282

为什么 ping 普通用户执行不要 root 权限？因为这些工具在管理员安装时就已经被赋予了一些必要的权限，具体请使用 `getcap /usr/bin/ping` 查看
