### ISSUE TITLE
leomoeapi 连接一直断

### ISSUE THREAD

**Issue by drickJK** [sjlleo/nexttrace#103]
国内用这个接口一直容易断，用起来体验不是很好，能不能优化一下

**Comment by tsosunchia** [comment]
由于本项目为非盈利开源项目，没有任何资金来源（现在的api服务器已经是项目组用爱发电了）考虑到成本因素，我们服务器架设于海外，并使用cloudflare作为CDN，如果国内访问出现连接中断属于正常现象。

您有两种变通方法：
- 使用国内访问良好的机器，自行架设反代服务器。
- 对使用nexttrace的计算机进行透明代理。

**Comment by drickJK** [comment]
> 由于本项目为非盈利开源项目，没有任何资金来源（现在的api服务器已经是项目组用爱发电了）考虑到成本因素，我们服务器架设于海外，并使用cloudflare作为CDN，如果国内访问出现连接中断属于正常现象。
> 
> 您有两种变通方法：
> 
> * 使用国内访问良好的机器，自行架设反代服务器。
> * 对使用nexttrace的计算机进行透明代理。

不能用腾讯云轻量服务器这种吗，如果没有的话我可以提供一台

**Comment by tsosunchia** [comment]
> > 由于本项目为非盈利开源项目，没有任何资金来源（现在的api服务器已经是项目组用爱发电了）考虑到成本因素，我们服务器架设于海外，并使用cloudflare作为CDN，如果国内访问出现连接中断属于正常现象。
> 
> > 
> 
> > 您有两种变通方法：
> 
> > 
> 
> > * 使用国内访问良好的机器，自行架设反代服务器。
> 
> > * 对使用nexttrace的计算机进行透明代理。
> 
> 
> 
> 不能用腾讯云轻量服务器这种吗，如果没有的话我可以提供一台

国内服务器由于政策、法律风险，一直没有考虑。而且轻量服务器的性能对于api服务器来说是不够用的。

**Comment by tsosunchia** [comment]
目前本项目还未考虑过在国内备案的可能，不备案的服务器是无法在国内合规使用的。

**Comment by drickJK** [comment]
> > > 由于本项目为非盈利开源项目，没有任何资金来源（现在的api服务器已经是项目组用爱发电了）考虑到成本因素，我们服务器架设于海外，并使用cloudflare作为CDN，如果国内访问出现连接中断属于正常现象。
> > 
> > 
> > > 
> > 
> > 
> > > 您有两种变通方法：
> > 
> > 
> > > 
> > 
> > 
> > > * 使用国内访问良好的机器，自行架设反代服务器。
> > 
> > 
> > > * 对使用nexttrace的计算机进行透明代理。
> > 
> > 
> > 不能用腾讯云轻量服务器这种吗，如果没有的话我可以提供一台
> 
> 国内服务器由于政策、法律风险，一直没有考虑。而且轻量服务器的性能对于api服务器来说是不够用的。

可以不开国内的，开东京，香港和新加坡

**Comment by tsosunchia** [comment]
> 由于本项目为非盈利开源项目，没有任何资金来源（现在的api服务器已经是项目组用爱发电了）考虑到成本因素，我们服务器架设于海外，并使用cloudflare作为CDN，如果国内访问出现连接中断属于正常现象。
> 
> 您有两种变通方法：
> - 使用国内访问良好的机器，自行架设反代服务器。
> - 对使用nexttrace的计算机进行透明代理。
> 

既然您有TYO、HKG国内访问良好的服务器，那就自行反代不就解决了？

**Comment by drickJK** [comment]
既然如此，能不能开放志愿者提供可用加速 ip，来加速国内访问

**Comment by tsosunchia** [comment]
> 既然如此，能不能开放志愿者提供可用加速 ip，来加速国内访问

您反代api.leo.moe就可以了，项目组自用的反代服务器就是这样的。（真实回源地址我们无法透露，之前被DDOS过）

**Comment by drickJK** [comment]
但是很多朋友不会反代，所以如果能开放公共加速服务器，我可以提供一个

**Comment by tsosunchia** [comment]
> 但是很多朋友不会反代，所以如果能开放公共加速服务器，我可以提供一个

最开始api.leo.moe国内访问是非常好的，但是在被多次攻击后，我们无奈地使用cloudflare保护我们的API，感谢您的建议，在时机成熟时我们会加以考虑的。

**Comment by drickJK** [comment]
> > 但是很多朋友不会反代，所以如果能开放公共加速服务器，我可以提供一个
> 
> 最开始api.leo.moe国内访问是非常好的，但是在被多次攻击后，我们无奈地使用cloudflare保护我们的API，感谢您的建议，在时机成熟时我们会加以考虑的。

好，如果后续需要请告诉我。
我可以冒昧问一下现在 api 的成本吗？

**Comment by tsosunchia** [comment]
> > > 但是很多朋友不会反代，所以如果能开放公共加速服务器，我可以提供一个
> 
> > 
> 
> > 最开始api.leo.moe国内访问是非常好的，但是在被多次攻击后，我们无奈地使用cloudflare保护我们的API，感谢您的建议，在时机成熟时我们会加以考虑的。
> 
> 
> 
> 好，如果后续需要请告诉我。
> 
> 我可以冒昧问一下现在 api 的成本吗？

数十 USD/month 这个量级，我们已经在尝试削减成本了。
