### ISSUE TITLE
报 `bash: /proc/self/fd/11: 没有那个文件或目录`   当我运行 `bash <(curl -Ls https://raw.githubusercontent.com/sjlleo/nexttrace/main/nt_install.sh)`

### ISSUE THREAD

**Issue by luojiyin1987** [sjlleo/nexttrace#104]
## 你正在使用哪个版本的 nexttrace？
使用 `sudo  bash <(curl -Ls https://raw.githubusercontent.com/sjlleo/nexttrace/main/nt_install.sh)`  一键安装  nexttrace

```shell
 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

## 你看到的异常现象是什么？
报错  
```shell
bash: /proc/self/fd/11: 没有那个文件或目录
```

## 你期待看到的正常表现是怎样的？
正常下载安装

## 请附上你的命令
```shell
bash <(curl -Ls https://raw.githubusercontent.com/sjlleo/nexttrace/main/nt_install.sh)
```

## 请附上出错时软件输出的错误信息
```shell
bash: /proc/self/fd/11: 没有那个文件或目录
```

## 我自己的解决办法
```shell
curl -Ls https://raw.githubusercontent.com/sjlleo/nexttrace/main/nt_install.sh | sudo  bash
```

**Comment by tsosunchia** [comment]
您可以通过`bash --version` 查看您的bash版本，bash <() 这个用法需要bash3.0以上。

**Comment by luojiyin1987** [comment]
只是 `sudo -i`   这样的操作，风险比较大。而且你未明确在readme 中说明。

**Comment by sjlleo** [comment]
Hi @luojiyin1987,

感谢您对我们开源项目的关注，并提供您宝贵的意见。

关于您提到的sudo -i命令风险的问题，我们理解您的担忧，但我们认为使用者在使用我们的项目之前就应该需要有一定的技术能力和安全意识，也知道这种操作可能会存在一定的风险。

不过，为了让我们的项目更加安全和可靠，未来我们会在README文件中增加一些关于此命令使用的说明和警告，以确保每个使用者都能够充分了解风险和注意事项。同时，我们也希望您能理解我们的立场，我们制作一键脚本本身旨在降低使用门槛。

再次感谢您对我们项目的支持和关注，祝您一切顺利！

Best Regards,
Leo Shen
