### ISSUE TITLE
关于自动上传路由数据的问题

### ISSUE THREAD

**Issue by bricklattice** [sjlleo/nexttrace#105]
我有一个疑问，就是为什么nexttrace会自动上传我的路由数据？

我想知道这样做的原因和用途是什么，为什么不默认关闭这个功能？以及这些数据会被如何处理和保护。我担心这样会泄露我的隐私或者影响我的网络安全。

我在使用nexttrace的时候，发现它会在每次路由跟踪结束后，向api.leo.moe发送一个POST请求，里面携带了我的路由数据。我希望你能解释一下这个功能的意义和必要性，以及是否有办法在不上传数据的情况下显示地图。

谢谢

**Comment by tsosunchia** [comment]
这个数据是显示tracemap的必要条件，如您不想使用该功能，可以关闭tracemap功能这样就不会上传了（相关参数可查询帮助文档）

**Comment by bricklattice** [comment]
这项功能应该默认关闭，而不是每次必须输入一个选项才能关闭。另外这些数据会被如何处理和保护？

**Comment by tsosunchia** [comment]
> 这项功能应该默认关闭，而不是每次必须输入一个选项才能关闭。另外这些数据会被如何处理和保护？

您可以自行修改相关代码，以达到默认关闭的目的。

**Comment by bricklattice** [comment]
> > 这项功能应该默认关闭，而不是每次必须输入一个选项才能关闭。另外这些数据会被如何处理和保护？
> 
> 您可以自行修改相关代码，以达到默认关闭的目的。

问题不在修改代码上，数据在上传前没有任何的提示，默认就传上去，没有经过我的同意

**Comment by tsosunchia** [comment]
关于此功能是否应该默认开启的讨论，我们已综合主要的服务对象的意见，并在之前的一次版本迭代中更改为默认开启。

**Comment by bricklattice** [comment]
请阅读欧盟的通用数据保护条例GDPR，个人数据必须使用假名化或匿名化进行存储，并且默认使用尽可能最高的隐私设置，以避免公开数据未经明确同意，并且不能用于识别没有单独存储附加信息的主题。

**Comment by sjlleo** [comment]
代码都已经开源，想要不被任何人知道，你可以自己搭建 tracemap 服务器，另外我们已经在 tracemap 中隐藏首跳的具体IP地址信息，至于你提到的 GDPR，强调的是个人数据必须使用假名化或匿名化进行存储，但是我们在 tracemap 中并没有泄露你的 IP 地址，也没有任何数据信息与你的个人身份所关联，如果你觉得这个软件侵犯到了你的个人隐私，你可以选择不用，并且联系我们删除所有可能相关的数据。
