### ISSUE TITLE
在Windows系统下，在nexttrace_windows_amd64.exe文件所在目录下进入cmd后输入该文件名无法使用该软件

### ISSUE THREAD

**Issue by luanshang** [sjlleo/nexttrace#115]

**Comment by tsosunchia** [comment]
有截图或log嘛？

**Comment by luanshang** [comment]
> 有截图或log嘛？

![image](https://github.com/sjlleo/nexttrace/assets/116410821/77c852d0-4e0f-471e-a65f-2dd6bda9540a)

**Comment by tsosunchia** [comment]
> > 有截图或log嘛？
> 
> 
> 
> ![image](https://github.com/sjlleo/nexttrace/assets/116410821/77c852d0-4e0f-471e-a65f-2dd6bda9540a)
> 
> 
请注意系统的错误提示，
系统的提示是正确的“在命令前加.\”

**Comment by luanshang** [comment]
> > > 有截图或log嘛？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/116410821/240237186-77c852d0-4e0f-471e-a65f-2dd6bda9540a.png)
> 
> 请注意系统的错误提示(倒数第二句话)， 系统的提示是正确的"在命令前加.\"
> 
> 若您想之后避免前面需要输入"."的情况，您可以将nexttrace移动到 c：\windows\system32文件夹下，这样就可以在任意位置使用nexttrace同时前面不加入“.”了

好了，多谢！

**Comment by Leao9203** [comment]
顺带一提，Scoop 的 extras 仓库也提供了 nexttrace，可以方便的进行更新，并且是放在 User 目录下的，避免了权限问题。
Name        : nexttrace
Description : An open source visual route tracking CLI tool
Version     : 1.1.6
Bucket      : extras
Website     : https://github.com/sjlleo/nexttrace
License     : GPL-3.0-or-later
Updated at  : 2023/5/30 4:23:45
Updated by  : github-actions[bot]
Installed   : 1.1.6
Binaries    : nexttrace.exe
