### ISSUE TITLE
控制台输出显示了错误的最大跳数

### ISSUE THREAD

**Issue by cmj2002** [sjlleo/nexttrace#116]
## 你正在使用哪个版本的 nexttrace？

linux_amd64 v1.1.4，在 WSL2 中运行

## 你看到的异常现象是什么？

~~添加参数 `-m 50` 之后最大跳数仍为 30~~

修改：添加参数后可以修改最大跳数，但是日志中仍然显示 `30 hops max`

## 你期待看到的正常表现是怎样的？

日志应当显示 `50 hops max`

## 请附上你的命令

`nexttrace -m 50 baidu.com`

## 请附上出错时软件输出的错误信息

```
NextTrace v1.1.4 2023-05-23T12:57:24Z b88d529
Please Choose the IP You Want To TraceRoute
0. 39.156.66.10
1. 110.242.68.66
Your Option: 0
[NextTrace API] prefered API IP - 104.19.28.108 - 81.09ms
IP Geo Data Provider: LeoMoeAPI
traceroute to 39.156.66.10 (baidu.com), 30 hops max, 32 byte packets
1   172.31.192.1    *        [RFC1918]        局域网
                                              0.81 ms / 0.71 ms / 0.66 ms
2   172.25.176.1    *        [RFC1918]        局域网
                                              4.87 ms / 23.62 ms / 18.31 ms
3   172.28.255.13   *        [RFC1918]        局域网
                                              225.64 ms / * ms / * ms
4   *
5   36.152.24.1     AS56046                   中国 江苏省 南京市  chinamobile.com  移动
                                              56.34 ms / 54.37 ms / 56.36 ms
6   *
7   *
8   221.183.37.233  AS9808   [CMNET]          中国 北京市   chinamobile.com  移动
                                              21.35 ms / * ms / 25.23 ms
9   221.183.49.134  AS9808   [CMNET]          中国 北京市   chinamobile.com  移动
                                              37.80 ms / 39.81 ms / 40.80 ms
10  111.13.0.174    AS9808   [CMNET]          中国 北京市   chinamobile.com  移动
                                              56.08 ms / 59.71 ms / 61.03 ms
11  39.156.27.5     AS9808                    中国 北京市   chinamobile.com  移动
                                              73.87 ms / 74.49 ms / 77.39 ms
12  39.156.67.17    AS9808                    中国 北京市   chinamobile.com  移动
                                              68.73 ms / 69.44 ms / 70.85 ms
13  *
14  10.166.96.12    *        [RFC1918]        局域网
                                              123.04 ms / * ms / * ms
15  10.166.3.2      *        [RFC1918]        局域网
                                              143.13 ms / 141.12 ms / * ms
16  39.156.66.10    AS9808                    中国 北京市   chinamobile.com  移动
                                              52.44 ms / * ms / 55.34 ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7f6778]

goroutine 1 [running]:
github.com/xgadget-lab/nexttrace/tracemap.GetMapUrl({0xc0004a8800, 0x4415})
        github.com/xgadget-lab/nexttrace/tracemap/tracemap.go:15 +0xb8
github.com/xgadget-lab/nexttrace/cmd.Excute()
        github.com/xgadget-lab/nexttrace/cmd/cmd.go:228 +0x168b
main.main()
        github.com/xgadget-lab/nexttrace/main.go:8 +0x17
```

**Comment by tsosunchia** [comment]
经过我的测试v1.1.4在windows/linux的amd64中v1.1.4是正常的
您此处的报错我猜测跟该参数无关，可能是网络原因导致

**Comment by tsosunchia** [comment]
> 相同环境下换了一个域名实验，在 `-m 50` 时日志仍显示错误，但最大跳数确实不是 30 行。然而仍然出现了相似的报错，可以发现 trace 已经完成，不知道是什么东西触发了报错，可能与 #106 相关。
> 
> ```
> $ nexttrace -m 50 microsoft.com
> NextTrace v1.1.4 2023-05-23T12:57:24Z b88d529
> Please Choose the IP You Want To TraceRoute
> 0. 20.84.181.62
> 1. 20.103.85.33
> 2. 20.81.111.85
> 3. 20.112.52.29
> 4. 20.53.203.50
> Your Option: 0
> [NextTrace API] prefered API IP - 104.19.28.108 - 99.09ms
> IP Geo Data Provider: LeoMoeAPI
> traceroute to 20.84.181.62 (microsoft.com), 30 hops max, 32 byte packets
> 1   172.31.192.1    *        [RFC1918]        局域网
>                                               0.65 ms / 0.71 ms / 0.68 ms
> 2   172.25.176.1    *        [RFC1918]        局域网
>                                               12.58 ms / 22.03 ms / 16.07 ms
> 3   172.28.255.13   *        [RFC1918]        局域网
>                                               233.36 ms / * ms / * ms
> 4   *
> 5   *
> 6   *
> 7   219.219.156.50  AS4538   [CERNET-CN]      中国 江苏省 南京市  cernet.edu.cn  教育网
>                                               * ms / * ms / 206.04 ms
> 8   101.4.116.98    AS4538   [BJR-CERNET]     中国 江苏省 南京市  cernet.edu.cn  教育网
>                                               8.76 ms / 9.71 ms / 12.44 ms
> 9   101.4.117.25    AS4538   [BJR-CERNET]     中国 安徽省 合肥市  cernet.edu.cn  教育网
>                                               * ms / 130.66 ms / 132.69 ms
> 10  101.4.112.61    AS4538   [BJR-CERNET]     中国 湖北省 武汉市  cernet.edu.cn  教育网
>                                               52.17 ms / 53.82 ms / 55.61 ms
> 11  101.4.115.201   AS4538   [BJR-CERNET]     中国 湖南省 长沙市  cernet.edu.cn  教育网
>                                               94.48 ms / 92.71 ms / 60.44 ms
> 12  *
> 13  101.4.114.194   AS4538   [BJR-CERNET]     中国 北京市   cernet.edu.cn  教育网
>                                               90.46 ms / 91.95 ms / 93.47 ms
> 14  101.4.114.182   AS4538   [BJR-CERNET]     中国 北京市   cernet.edu.cn  教育网
>                                               107.98 ms / 109.50 ms / 110.63 ms
> 15  101.4.117.69    AS4538   [BJR-CERNET]     中国 北京市   cernet.edu.cn  教育网
>                                               124.81 ms / 126.32 ms / 127.66 ms
> 16  203.131.254.213 AS2914   [NTT-GLOBAL]     中国 香港   ntt.net
>                                               141.01 ms / 146.62 ms / 146.76 ms
> 17  129.250.5.162   AS2914   [NTT-BACKBONE]   中国 香港   ntt.net
>                                               157.23 ms / 159.76 ms / 160.67 ms
> 18  129.250.6.94    AS2914   [NTT-BACKBONE]   中国 香港   ntt.net
>                                               73.70 ms / 75.72 ms / 75.22 ms
> 19  128.241.8.227   AS2914   [NTTA-128]       中国 香港   ntt.net
>                                               89.79 ms / 93.97 ms / 91.98 ms
> 20  104.44.42.190   AS8075   [MSFT]           中国 香港   microsoft.com
>                                               104.40 ms / 105.89 ms / 109.12 ms
> 21  104.44.11.131   AS8075   [MSFT]           中国 香港   microsoft.com
>                                               326.24 ms / 328.49 ms / 329.79 ms
> 22  104.44.17.100   AS8075   [MSFT]           日本 东京都 东京  microsoft.com
>                                               342.64 ms / 345.03 ms / 346.73 ms
> 23  104.44.16.43    AS8075   [MSFT]           日本 东京都 东京  microsoft.com
>                                               359.68 ms / 363.69 ms / 365.37 ms
> 24  104.44.18.167   AS8075   [MSFT]           美国 俄勒冈州 波特兰  microsoft.com
>                                               * ms / * ms / 375.70 ms
> 25  104.44.7.101    AS8075   [MSFT]           美国 俄勒冈州 波特兰  microsoft.com
>                                               290.38 ms / 295.41 ms / 296.19 ms
> 26  104.44.16.70    AS8075   [MSFT]           美国 华盛顿州 昆西  microsoft.com
>                                               310.71 ms / 309.09 ms / 310.89 ms
> 27  104.44.19.45    AS8075   [MSFT]           德国 黑森州 美茵河畔法兰克福  microsoft.com
>                                               327.94 ms / 326.89 ms / 333.38 ms
> 28  104.44.19.87    AS8075   [MSFT]           美国 艾奥瓦州 得梅因  microsoft.com
>                                               * ms / 341.65 ms / 549.36 ms
> 29  104.44.32.63    AS8075   [MSFT]           美国 艾奥瓦州 得梅因  microsoft.com
>                                               357.15 ms / 360.07 ms / 362.24 ms
> 30  *
> 31  *
> 32  *
> 33  *
> 34  *
> 35  20.84.181.62    AS8075                    美国 艾奥瓦州 得梅因  microsoft.com
>                                               352.28 ms / 353.51 ms / 355.19 ms
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7f6778]
> 
> goroutine 1 [running]:
> github.com/xgadget-lab/nexttrace/tracemap.GetMapUrl({0xc00089c000, 0xba02})
>         github.com/xgadget-lab/nexttrace/tracemap/tracemap.go:15 +0xb8
> github.com/xgadget-lab/nexttrace/cmd.Excute()
>         github.com/xgadget-lab/nexttrace/cmd/cmd.go:228 +0x168b
> main.main()
>         github.com/xgadget-lab/nexttrace/main.go:8 +0x17
> ```

猜测原因可能是您的服务器与绘制TRACEMAP的API的连接有问题

**Comment by cmj2002** [comment]
我也认为是这个原因。

不过日志显示错误的问题确实是存在的，我把 issue 标题修改一下。

**Comment by tsosunchia** [comment]
> 我也认为是这个原因。
> 
> 不过日志显示错误的问题确实是存在的，我把 issue 标题修改一下。

github.com/xgadget-lab/nexttrace/tracemap.GetMapUrl({0xc00089c000, 0xba02})
        github.com/xgadget-lab/nexttrace/tracemap/tracemap.go:15 +0xb8
这里的错误日志也指向tracemap了

**Comment by tsosunchia** [comment]
我已经在最新的commit ac1ee5 中增加该部分的异常处理，至少类似问题会显示"An issue occurred while connecting to the Tracemap API."
您可以在最新的[action](https://github.com/sjlleo/nexttrace/actions/runs/5066230988)处下载编译好的二进制文件，应该会解决您的问题。

**Comment by cmj2002** [comment]
经过测试，可以显示 `An issue occurred while connecting to the tracemap API.`

也请您修复一下日志中对最大跳数描述错误的问题，目前无论 `-m` 如何指定，日志（即 `traceroute to 39.156.66.10 (baidu.com), 30 hops max, 32 byte packets` 这一行）都仍然会输出 30。

**Comment by tsosunchia** [comment]
> 经过测试，可以显示 `An issue occurred while connecting to the tracemap API.`
> 
> 也请您修复一下日志中对最大跳数描述错误的问题，目前无论 `-m` 如何指定，日志（即 `traceroute to 39.156.66.10 (baidu.com), 30 hops max, 32 byte packets` 这一行）都仍然会输出 30。

哦 我明白了 非常感谢你提出这个问题 之前我们一直没注意到这个问题
现在已经在最新的 commit  3084eff 中修复这个问题，您可以在[最新的action](https://github.com/sjlleo/nexttrace/actions/runs/5066482210)处下载编译好的二进制文件，应该会解决您的问题。

**Comment by tsosunchia** [comment]
如果您之后还发现任何问题，欢迎您再次来提出ISSUE或PR
