### ISSUE TITLE
nexttrace 未来是否会继续维护

### ISSUE THREAD

**Issue by flaskingnet** [sjlleo/nexttrace#117]
开发组你们好

我们开发小组对你们项目功能有一定需求，所以想使用这个项目的软件，但是我看到你们项目似乎并没有商业化，那你们项目是否会继续做下去？

用爱发电的项目一般无法支撑太长时间

谢谢

**Comment by tsosunchia** [comment]
>我们开发小组对你们项目功能有一定需求，所以想使用这个项目的软件
可以问一下你们是想做什么软件吗？
>我看到你们项目似乎并没有商业化，那你们项目是否会继续做下去？
NEXTTRACE的设计一直是致力于支持更多的第三方GEOIP API，就算是我们官方的API不再维护，也能让NEXTTRACE使用集成的其他GEOIP API继续长久的使用下去，况且我们的软件本体以及后端都是开源的，若我们不再维护官方的API，开源社区的其他用户也可以自行架设我们官方API的同款，所以我想这方面也是不用担心的。
>用爱发电的项目一般无法支撑太长时间
目前可以确定是的官方API的服务器在不出现重大变故的情况下是能运行到24年的。

**Comment by flaskingnet** [comment]
> > 我们开发小组对你们项目功能有一定需求，所以想使用这个项目的软件
> 
> 可以问一下你们是想做什么软件吗？

我们正在做 cdn 的分布式监控服务，但是中间需要记录路由的数据并且存储分析，我们整套架构还是基于 python 和 go 的，但是类似的开源产品不多，通过各种推荐发现了这个

**Comment by tsosunchia** [comment]
> > > 我们开发小组对你们项目功能有一定需求，所以想使用这个项目的软件
> > 
> > 
> > 可以问一下你们是想做什么软件吗？
> 
> 我们正在做 cdn 的分布式监控服务，但是中间需要记录路由的数据并且存储分析，我们整套架构还是基于 python 和 go 的，但是类似的开源产品不多，通过各种推荐发现了这个

关于LEOMOEAPI(即NEXTTRACE官方API)由于版权原因，是不允许其他软件使用的。
见README这部分：
>该接口未经允许不可用于任何第三方用途。

**Comment by flaskingnet** [comment]
> > > > 我们开发小组对你们项目功能有一定需求，所以想使用这个项目的软件
> > > 
> > > 
> > > 可以问一下你们是想做什么软件吗？
> > 
> > 
> > 我们正在做 cdn 的分布式监控服务，但是中间需要记录路由的数据并且存储分析，我们整套架构还是基于 python 和 go 的，但是类似的开源产品不多，通过各种推荐发现了这个
> 
> 关于LEOMOEAPI(即NEXTTRACE官方API)由于版权原因，是不允许其他软件使用的。 见README这部分：
> 
> > 该接口未经允许不可用于任何第三方用途。
> > LeoMoeAPI 早期数据主要来自 IPInsight、IPInfo，随着项目发展，越来越多的志愿者参与进了这个项目。目前 LeoMoeAPI 有近一半的数据是社区提供的，而另外一半主要来自于包含 IPInfo、IPData、BigDataCloud、IPGeoLocation 在内的多个第三方数据。

我们不将它用在别的软件，我们的脚本会运行 nexttrace 然后解析日志存放在库中分析

**Comment by tsosunchia** [comment]
> > > > > 我们开发小组对你们项目功能有一定需求，所以想使用这个项目的软件
> > > > 
> > > > 
> > > > 可以问一下你们是想做什么软件吗？
> > > 
> > > 
> > > 我们正在做 cdn 的分布式监控服务，但是中间需要记录路由的数据并且存储分析，我们整套架构还是基于 python 和 go 的，但是类似的开源产品不多，通过各种推荐发现了这个
> > 
> > 
> > 关于LEOMOEAPI(即NEXTTRACE官方API)由于版权原因，是不允许其他软件使用的。 见README这部分：
> > > 该接口未经允许不可用于任何第三方用途。
> > > LeoMoeAPI 早期数据主要来自 IPInsight、IPInfo，随着项目发展，越来越多的志愿者参与进了这个项目。目前 LeoMoeAPI 有近一半的数据是社区提供的，而另外一半主要来自于包含 IPInfo、IPData、BigDataCloud、IPGeoLocation 在内的多个第三方数据。
> 
> 我们不将它用在别的软件，我们的脚本会运行 nexttrace 然后解析日志存放在库中分析

您说的这种情况，我不确定是否在可授权范围内，需要等待 LEOMOEAPI @sjlleo 回答。

不过关于对一些网络链路进行实时持续的监控，我个人认为MTR等不带GEOIP功能的工具更加合适(因为这种情况不需要每次trace都要解析一遍每一HOP的GEOIP信息，仅第一次和变更时需要解析，而且我们的API服务的性能不能支撑大量持续的请求)

**Comment by flaskingnet** [comment]
我们也需要地理位置信息，目前网上出售的骨干网数据不能满足我们的要求，nexttrace 基本可以满足

**Comment by sjlleo** [comment]
NextTrace 的 API 不能用于商业用途
