### ISSUE TITLE
关于近期 LeoMoeAPI 服务出现大量错误数据声明及后续措施

### ISSUE THREAD

**Issue by sjlleo** [sjlleo/nexttrace#119]
各位 NextTrace 用户，

我代表项目管理团队，写下这份致歉声明，向您解释最近关于我们的LeoMoeAPI服务中出现的一系列问题，以及我们已采取的相应措施。

近期，我们发现在我们的数据库中存在大量错误数据，这导致了我们的LeoMoeAPI服务无法正常提供稳定可靠的路由跟踪 IP 地理位置服务。在我们进行深入调查之后，发现这些错误数据的产生与我们开源项目团队的一位成员A及其朋友B的行为有关。成员A不慎将他的访问密钥分享给了朋友B，朋友B因为个人喜好，将大量错误数据插入到我们的数据库中。

值得指出的是，当我们找到朋友B时，他起初并未承认这是他所为，但在我们出示了日志记录的确凿证据后，他才承认了自己的行为。他的态度显然显示出一种轻浮和不负责任的态度，他将此行为仅视为一种"好玩"的行为，并认为“就是改了点数据，没什么大不了的”。

这种行为对我们的服务的数据准确性造成了严重影响，导致了一系列的问题（Prefix IP 段查找异常），需要我们花费大量的时间和精力去修复。这种情况更是给我们的用户的路由信息带来了很多误解，我们深感遗憾。

针对本次事件，我们已经采取了一系列的应对措施。其中，我们已经暂时撤回了所有密钥的权限，并且我们已决定**LeoMoeAPI将永远不收录B的ASN，同时也拒绝为他的ASN提供一切服务**。这是对他**不负责任的行为的严肃回应**，我们希望这将作为一个强有力的警示，确保我们的开源项目社区成员理解自己的行为责任。

我们强烈呼吁，每位成员都需负责任地对待自己的权限，保护自己的访问密钥，并尽量避免任何可能损害我们的开源项目的行为。

最后，我们非常感谢社区的理解和支持，我们在未来会采取更多有效行动避免此事的再度发生。

谢谢！

Best Regards,
Leo Shen

**Comment by Fangliding** [comment]
这这不能

**Comment by flaskingnet** [comment]
你们为什么会允许非项目组成员修改数据 这样迟早会出问题的吧

**Comment by tsosunchia** [comment]
> 你们为什么会允许非项目组成员修改数据 这样迟早会出问题的吧

精力有限，只能选择相信开源社区的素质了（）

**Comment by flaskingnet** [comment]
> > 你们为什么会允许非项目组成员修改数据 这样迟早会出问题的吧
> 
> 精力有限，只能选择相信开源社区的素质了（）

国内的社区环境你们又不是不知道 “小学生”横行的

**Comment by tsosunchia** [comment]
> > > 你们为什么会允许非项目组成员修改数据 这样迟早会出问题的吧
> > 
> > 
> > 精力有限，只能选择相信开源社区的素质了（）
> 
> 国内的社区环境你们又不是不知道 “小学生”横行的

所以以后只能收紧权限以及加强审计和日志了

**Comment by sjlleo** [comment]
基本已经 Fix，后续继续观察。

**Comment by sjlleo** [comment]
后续如果有任何问题，请随时在此 issue 底下提出，我看到后会第一时间来继续排查，Thanks!

**Comment by QiTianzu** [comment]
还没有恢复吗？

**Comment by sjlleo** [comment]
> 还没有恢复吗？

Cloudsigma had a planned maintenance, now it's available. 

This affects China Users only. More detail can be found below this. Thank you.

![图片](https://github.com/sjlleo/nexttrace/assets/13616352/5f36acee-572d-4ca1-a35a-aae54b6039cf)

**Comment by QiTianzu** [comment]
> > 还没有恢复吗？
> 
> 3天前就修复了
> 
> > 基本已经 Fix，后续继续观察。
> 
> 你遇到什么问题了吗？

一开始没有防火墙放行 ICMP 协议，跟踪结果都是 * 号，放行之后跟踪结果有 IP 地址了，但最后还是显示 an issue occurred while connecting to the tracemap API

**Comment by tsosunchia** [comment]
> > > 还没有恢复吗？
> > 
> > 
> > 3天前就修复了
> > > 基本已经 Fix，后续继续观察。
> > 
> > 
> > 你遇到什么问题了吗？
> 
> 一开始没有防火墙放行 ICMP 协议，跟踪结果都是 * 号，放行之后跟踪结果有 IP 地址了，但最后还是显示 an issue occurred while connecting to the tracemap API

您可以再试试，大陆地区使用的服务器刚才维护了一会

**Comment by QiTianzu** [comment]
> > > > 还没有恢复吗？
> > > 
> > > 
> > > 3天前就修复了
> > > > 基本已经 Fix，后续继续观察。
> > > 
> > > 
> > > 你遇到什么问题了吗？
> > 
> > 
> > 一开始没有防火墙放行 ICMP 协议，跟踪结果都是 * 号，放行之后跟踪结果有 IP 地址了，但最后还是显示 an issue occurred while connecting to the tracemap API
> 
> 您可以再试试，大陆地区使用的服务器刚才维护了一会

还是不行，试几十次只有一两次有 URL

**Comment by tsosunchia** [comment]
> > > > > 还没有恢复吗？
> > > > 
> > > > 
> > > > 3天前就修复了
> > > > > 基本已经 Fix，后续继续观察。
> > > > 
> > > > 
> > > > 你遇到什么问题了吗？
> > > 
> > > 
> > > 一开始没有防火墙放行 ICMP 协议，跟踪结果都是 * 号，放行之后跟踪结果有 IP 地址了，但最后还是显示 an issue occurred while connecting to the tracemap API
> > 
> > 
> > 您可以再试试，大陆地区使用的服务器刚才维护了一会
> 
> 还是不行，试几十次只有一两次有 URL

那大概就是您的网络与服务器连接的问题了，您可以试试修改/etc/hosts，选择一些连接良好的cloudflare IP强制api.leo.moe选择那些进行连接。

**Comment by Leao9203** [comment]
想提个小建议，能否通过 git 的方式来更新 IP 数据库，之后通过提交 PR 来更新数据库？
