### ISSUE TITLE
能否加个线路判断

### ISSUE THREAD

**Issue by flaskingnet** [sjlleo/nexttrace#120]
以前看到有个脚本会显示线路有普通 精品 高端

**Comment by tsosunchia** [comment]
我非常清楚您说的是哪个脚本，那个脚本确实帮助了很多小白理解线路，但是其争议太大，有很多不准确的判断（判断还是需要人工的）导致有很多负面评价。
况且此功能完全也可以方便的使用shell命令完成，若加入软件本体将导致很多维护问题，比如fasttrace功能我们的设想也是时机成熟后将其独立出来并从本体移除。
再次感谢您的建议。

**Comment by flaskingnet** [comment]
这个功能应该也可以自动做吧

**Comment by tsosunchia** [comment]
> 这个功能应该也可以自动做吧

是可以，但是任何不全面的判断都会利于商家的针对性造假。
综上，此功能不会加入nexttrace本体中，您可以另写一个脚本调用nexttrace实现类似的逻辑。

**Comment by flaskingnet** [comment]
> > 这个功能应该也可以自动做吧
> 
> 是可以，但是任何不全面的判断都会利于商家的针对性造假。 综上，此功能不会加入nexttrace本体中，您可以另写一个脚本调用nexttrace实现类似的逻辑。

有没有可以参考的逻辑 谢谢

**Comment by tsosunchia** [comment]
GITHUB有类似的项目，你可以自行查阅，我认为那些脚本的检测方法都有明显的问题，就不做推介了。
