### ISSUE TITLE
建议加上一些声明

### ISSUE THREAD

**Issue by flaskingnet** [sjlleo/nexttrace#121]
nexttrace不太适合没有经验的人使用 我在介绍给朋友的时候正好被旁边的新人看到了 新人还是喜欢一些傻瓜式界面 有一键脚本可以选地区的那些

**Comment by isyekong** [comment]
这只是一个路由追踪工具，类似于 MTR、Traceroute 
用来帮助用户了解路由，不需要地区选择

**Comment by flaskingnet** [comment]
加上测试起来会比较方便 否则ip不好找 谢谢

**Comment by tsosunchia** [comment]
此类问题昨天已经回答过，不再赘述
