### ISSUE TITLE
在安卓上工作时dns错误

### ISSUE THREAD

**Issue by Fangliding** [sjlleo/nexttrace#125]
## 你正在使用哪个版本的 nexttrace？

nexttrace_linux_arm64

## 你看到的异常现象是什么？

dns无法解析
写域名 报错Domain baidu.com Lookup Fail
直接写ip报错DNS resolution failed, please check your system DNS Settings

命令就是./nexttrace xxxxx

如果可以正常输出报错的话那我应该没选错平台 环境是termux 已经赋予运行权限 以root执行

**Comment by tsosunchia** [comment]
你TG直接私聊我吧，解决后我视情况总结后发到此issue

**Comment by tsosunchia** [comment]
问题详情：
- 运行nexttrace时报错`DNS resolution failed, please check your system DNS Settings`
- `nslookup baidu.com` 正常
- 使用--dot-server参数也失败
- `dig @::1 baidu.com A` 失败

> 只需创建`/etc/resolv.conf`并附加`nameserver 8.8.8.8`，然后这个问题就会得到解决。

引自：https://stackoverflow.com/questions/38959067/dns-lookup-issue-when-running-my-go-app-in-termux

此issue提到的问题已加入仓库wiki，非常感谢您的反馈，如果还有任何其他问题，欢迎再次联系我们。
