### ISSUE TITLE
brew 安装报错

### ISSUE THREAD

**Issue by wingofsky** [sjlleo/nexttrace#46]
## 你正在使用哪个版本的 nexttrace？

macOS_arm64
MacBook Air (M1, 2020)

## 你看到的异常现象是什么？

```shell
brew tap xgadget-lab/nexttrace
brew install nexttrace
Error: nexttrace: undefined local variable or method `null' for #<Class:0x00007fe3b7dc1fe8>
```
<img width="746" alt="image" src="https://user-images.githubusercontent.com/1725695/201652992-5079351f-2148-4f45-83c9-1d050266b32b.png">

## 你期待看到的正常表现是怎样的？
正常安装

## 请附上你的命令
brew install nexttrace

## 请附上出错时软件输出的错误信息
Error: nexttrace: undefined local variable or method `null' for #<Class:0x00007fe3b7dc1fe8>

**Comment by sjlleo** [comment]
修复了，重新试试~

**Comment by wingofsky** [comment]
> 修复了，重新试试~

还是不行，需要我提供其他什么信息吗？

<img width="760" alt="image" src="https://user-images.githubusercontent.com/1725695/201906531-740dfa3f-6015-43bc-aa1e-1efcebc16395.png">

**Comment by 0x0021** [comment]
```bash
└─[$] brew install nexttrace                                                                                [9:25:46]
Running `brew update --auto-update`...
Error: nexttrace: undefined local variable or method `null' for #<Class:0x00007fe95995afc0>
```

**Comment by sjlleo** [comment]
> ```shell
> └─[$] brew install nexttrace                                                                                [9:25:46]
> Running `brew update --auto-update`...
> Error: nexttrace: undefined local variable or method `null' for #<Class:0x00007fe95995afc0>
> ```

抱歉，因为目前我手里没有 macOS 环境，此问题也未能查出原因，故只能暂时搁置，请至 release 下载最新版本，谢谢。

**Comment by tsosunchia** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/59512455/212226368-9896c4a4-7ecf-42fb-a5d8-bc1612b3187b.png">
经测试我这里使用homebrew安装是没有问题的(macOS13.1 M1)，
建议您使用更换网络环境再试试(此类问题大多数是网络问题导致的)，

**【重试前请务必完整卸载之前的残留】**

```shell
brew uninstall nexttrace
brew untap xgadget-lab/nexttrace
brew cleanup
```

如果还是不行，方便的话请提交verbose模式截图。
```shell
brew tap xgadget-lab/nexttrace -v
brew install nexttrace -v
```

**Comment by wingofsky** [comment]
> <img alt="image" width="716" src="https://user-images.githubusercontent.com/59512455/212228435-6d4c8006-d130-4f0e-9616-8796becdb437.png">
> 
> 经测试我这里使用homebrew安装是没有问题的(macOS13.1 M1)， 建议您使用更换网络环境再试试(此类问题大多数是网络问题导致的)，
> 
> **【重试前请务必完整卸载之前的残留】**
> 
> ```shell
> brew uninstall nexttrace
> brew untap xgadget-lab/nexttrace
> brew cleanup --prune=all
> ```
> 
> 如果还是不行，方便的话请提交verbose模式截图。
> 
> ```shell
> brew tap xgadget-lab/nexttrace -v
> brew install nexttrace -v
> ```

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/1725695/212468463-aa14b299-b524-4fbd-940c-c98c06ed07f0.png">


<img width="1270" alt="image" src="https://user-images.githubusercontent.com/1725695/212468491-c9f099a1-e226-472e-a52a-e489a6c712fc.png">

**Comment by sjlleo** [comment]
@tsosunchia 会不会是因为brew使用了镜像的关系，我看有的镜像未必会全部缓存全部的包，这里似乎清华的源找不到 go 1.19.4 的 go 二进制包，导致出了问题。

**Comment by tsosunchia** [comment]
> @tsosunchia 会不会是因为brew使用了镜像的关系，我看有的镜像未必会全部缓存全部的包，这里似乎清华的源找不到 go 1.19.4 的 go 二进制包，导致出了问题。

这我不太清楚，我使用的是官方源

**Comment by wingofsky** [comment]
> @tsosunchia 会不会是因为brew使用了镜像的关系，我看有的镜像未必会全部缓存全部的包，这里似乎中科大的源找不到 go 1.19.4 的 go 二进制包，导致出了问题。

我去换成官方源试下

**Comment by sjlleo** [comment]
> > @tsosunchia 会不会是因为brew使用了镜像的关系，我看有的镜像未必会全部缓存全部的包，这里似乎清华的源找不到 go 1.19.4 的 go 二进制包，导致出了问题。
> 
> 这我不太清楚，我使用的是官方源

对了，后面 0.3.0 版本要来了，之前不是咱加了 ipv6 的包校验吗，这次我把包括 ipv4 在内整个重写了，而且发包太慢了，如果遇到rDNS服务器无响应的就要卡半天。

0.3.0 首先改了包的id校验，把最后一个二进制位变成了一个奇偶校验，然后把ttl也塞进去了，应该能彻底过滤掉不符合条件的ipv6包。

之前那种修改办法确实可以让错误的包过滤，但是依旧会影响延时，所以后面的延时会变成接近0ms，现在应该就不会了。

另外彻底改成了像 besttrace 和 mtr 一样的异步请求，应该会快很多。

这次动的东西很多，但是我猜可能有 Bug，我打算先放到 enhanced 编译一个版本去看看有没有奇奇怪怪的问题，想来试试吗？

**Comment by tsosunchia** [comment]
> > > @tsosunchia 会不会是因为brew使用了镜像的关系，我看有的镜像未必会全部缓存全部的包，这里似乎清华的源找不到 go 1.19.4 的 go 二进制包，导致出了问题。
> > 
> > 这我不太清楚，我使用的是官方源
> 
> 对了，后面 0.3.0 版本要来了，之前不是咱加了 ipv6 的包校验吗，这次我把包括 ipv4 在内整个重写了，而且发包太慢了，如果遇到rDNS服务器无响应的就要卡半天。
> 
> 0.3.0 首先改了包的id校验，把最后一个二进制位变成了一个奇偶校验，然后把ttl也塞进去了，应该能彻底过滤掉不符合条件的ipv6包。
> 
> 之前那种修改办法确实可以让错误的包过滤，但是依旧会影响延时，所以后面的延时会变成接近0ms，现在应该就不会了。
> 
> 另外彻底改成了像 besttrace 和 mtr 一样的异步请求，应该会快很多。
> 
> 这次动的东西很多，但是我猜可能有 Bug，我打算先放到 enhanced 编译一个版本去看看有没有奇奇怪怪的问题，想来试试吗？

没问题（commit之后at我就行了）

**Comment by wingofsky** [comment]
> ```shell
> brew install nexttrace -v
> ```

换成官方源，安装成功！谢谢！
