### ISSUE TITLE
能否通过setcap添加capabilities在普通用户下执行

### ISSUE THREAD

**Issue by kdurov** [sjlleo/nexttrace#48]
`sudo setcap cap_net_raw,cap_net_admin+eip ~/.bin/nexttrace`
添加后还是会提示需要 root 权限。
能否让普通用户也能执行呢？

谢谢

**Comment by sjlleo** [comment]
如无其他问题，此 issue 将被关闭，如果仍有疑问请另提新 issue

**Comment by kdurov** [comment]
谢谢。
刚测试本地环境无问题。

**Comment by kdurov** [comment]
macOS 下没有 setcap。
想请教下有什么别的办法能在 macOS 普通用户下执行么？

**Comment by sjlleo** [comment]
对于 macOS (Darwin) 来说，权限设计是更为严格的。可惜目前 macOS 并没有能够达到 setcap 相似功能的指令集，NextTrace 的 `net_raw` （原始包监听）是必要的一个权限，对于 Go 开发的路由跟踪，可能目前没有很好的办法去避免（除非使用 `syscall`，但是 `syscall` 也会涉及到 root 权限的需要）。

网上也有很多关于这方面的讨论，目前对于 macOS 来说，只能通过 sudo 或者以 root 用户运行。
这些内容可能对你有所帮助：
1. https://news.ycombinator.com/item?id=14168124
2. https://unix.stackexchange.com/questions/271819/enable-linux-capabilities-on-macos

Thanks.

**Comment by kdurov** [comment]
感谢指教。

看来只能通过 alias 配合 visudo 简化命令了。
