### ISSUE TITLE
使用M参数后，不显示MapTrace URL

### ISSUE THREAD

**Issue by fe6520** [sjlleo/nexttrace#54]
## 你正在使用哪个版本的 nexttrace？

linux_amd64-v0.2.6

## 你看到的异常现象是什么？

使用M参数不显示地图URL

## 你期待看到的正常表现是怎样的？

能正常显示地图照片

## 请附上出错时软件输出的错误信息
![FS](https://user-images.githubusercontent.com/18222783/212230469-aa64c8d5-ccdf-4117-9cf0-88dab16d95b9.png)

**Comment by sjlleo** [comment]
Hi @fe6520,

很抱歉，这似乎某次更新以后，Nginx在做路径分流时后端转发到了错误的服务器上，我们现在已经确认这个问题，并正在调查。

请耐心等待我们修复。

感谢您上报此错误。

**Comment by sjlleo** [comment]
请您再试一下，现在应该已经正常工作了

**Comment by fe6520** [comment]
> 请您再试一下，现在应该已经正常工作了

完美，现在可以显示了。
![Snipaste_2023-01-13_12-26-08](https://user-images.githubusercontent.com/18222783/212237317-c45f4849-df9e-4dfb-9062-d2aba903b6f7.png)

**Comment by sjlleo** [comment]
> 感谢！

等等，似乎还有个问题，每个节点点开应该是显示英文的地理位置信息的，不知为何变成了乱码，我现在去看以下。

**Comment by sjlleo** [comment]
好了，再试试哦，之前忘记了 NextTrace 上报的数据默认是不传英文数据的，所以出现了乱码，现在已经对其进行 UTF-8 解码，从而恢复了正常。
