### ISSUE TITLE
有没有对外提供api接口

### ISSUE THREAD

**Issue by plasmafree** [sjlleo/nexttrace#58]
对你们一些ipv6的数据感兴趣 有无提供接口

**Comment by isyekong** [comment]
目前暂无公开的接口，但我好奇您要做什么内容？

**Comment by plasmafree** [comment]
日志分析用

**Comment by sjlleo** [comment]
Hi [plasmafree](https://github.com/plasmafree),

我们没有计划对外提供 API 服务，如果您有日志分析的需求，建议您使用其他 IPv6 数据库。
