### ISSUE TITLE
请求支持packets设置

### ISSUE THREAD

**Issue by imSpecialforces** [sjlleo/nexttrace#62]
请求在支持packets设置，有些无良互联网服务提供商会设置相应路由策略，标准包大小会走更优秀的路由。

**Comment by sjlleo** [comment]
> 请求在支持packets设置，有些无良互联网服务提供商会设置相应路由策略，标准包大小会走更优秀的路由。

您好，

首先，感谢您的建议。

NextTrace 有自己的开发规划，此功能目前不在我们会实现的开发计划中。

我们已经把它加入了我们 TODO 中，我们会研究它的可行性，然后在未来我们可能会在某个版本实现这个功能。

如果您很希望立即拥有这个功能，我们欢迎您fork并向我们提交pull request，我们会很乐意merge这个功能的相关代码，并把您加入贡献者名单中。

如果您可以自己编译代码，我可以告诉您包data的封装部分，在 trace 文件夹 icmp_v4.go 中的第254行（icmp_v6.go 同理），手动改动data里 []byte的消息长度并重新编译即可。

另外，NextTrace 默认没有使用系统的依赖来发包，因为校验模块的变动，包大小也并非标准的64Byte。

谢谢

**Comment by sjlleo** [comment]
如无其他问题，本 issue 将被关闭，如有其他疑虑，请另起新 issue
