### ISSUE TITLE
请求支持模拟发包和延时预测

### ISSUE THREAD

**Issue by plasmafree** [sjlleo/nexttrace#63]
请求支持在不进行真实路由跟踪时 通过服务器ip能够得出路由结果 同时可以支持未来几小时的延时变动情况

**Comment by sjlleo** [comment]
您好，

如果你要在不进行实际的 Traceroute 的情况下，仅根据服务器 IP 的 ASN 以及 Peer 信息来推测路由跟踪结果，这是极其困难的。

NextTrace 不是一个做深度学习相关的项目，况且我们也没有那么多样本数据供机器学习，更不用说去推测未来几小时的延时变动情况。

谢谢

**Comment by plasmafree** [comment]
有没有做这方面产品的

**Comment by stydxm** [comment]
预测怎么可能，海缆断了或者运营商切线路这种事件在小小一台机器上根本无法提前获知，就算知道了也没法算出延迟

**Comment by plasmafree** [comment]
> 预测怎么可能，海缆断了或者运营商切线路这种事件在小小一台机器上根本无法提前获知，就算知道了也没法算出延迟

不能拿到对面机器 想知道对面机器回程 现在没有软件提供这样功能的 对我很有用 延迟给个区间 大致情况了解就可以

**Comment by sjlleo** [comment]
您是想说，您希望 NT 增加一个功能，可以看任意个 IP 的反向路由？不仅能看到走了什么骨干网，还能看到这些骨干网真实的 IP Path 和延时，同时要这里面 IP 的未来三小时延时变化趋势。我理解的没错吧？
