### ISSUE TITLE
digitalocean 数据不准

### ISSUE THREAD

**Issue by slogase** [sjlleo/nexttrace#66]
全错的

**Comment by slogase** [comment]
amazon也不准

**Comment by tsosunchia** [comment]
因为我们没有aws和do的机子，所以近期无法做校准。
如果可以的话，您也可以向我们提交数据以纠正，谢谢。

**Comment by isyekong** [comment]
![image](https://user-images.githubusercontent.com/20068143/215037303-a2002145-bdc8-4066-a467-23ad303ac695.png)

![image](https://user-images.githubusercontent.com/20068143/215037444-6f95b5b2-ea56-4176-b3b0-146b6df97e8b.png)

随便测了两个是没问题的，如果您是说云服务商的骨干网数据，这部分数据云厂并没有公开，我们没有那么多地区的 VM 用于测试校准。
特别是 AWS IPv6 骨干网目前并没有稳定下来，随时可能会变，无法确定实际位置。

建议您向我们提交数据以纠正，谢谢。

**Comment by slogase** [comment]
ipv6不准 拿besttrace测没问题

**Comment by tsosunchia** [comment]
> ipv6不准 拿besttrace测没问题

您能提供一下数据嘛

**Comment by sjlleo** [comment]
> ipv6不准 拿besttrace测没问题

有件事情想向您请教一下，您知道 NextTrace 和 BestTrace 是 2 个用在完全不一样用途上的软件吗？

无论是侧重点还是开发方向都完全不一样，如果您不知道的话，建议别用 NextTrace，何必给自己添堵呢（
