### ISSUE TITLE
NextTrace 将结束对 Classic 显示模式的支持

### ISSUE THREAD

**Issue by sjlleo** [sjlleo/nexttrace#72]
作为 NextTrace 最为古老的显示模式之一，考虑到目前已经鲜有用户依旧在使用它，我们认为再维护一个这样的模式会造成很大程度上的兼容负担，所以 1.0.8 将成为最后一个支持 classic 显示的版本，从 1.0.9 开始，这个模式将彻底被移除，这将方便我们对一部分结构进行进一步的优化。

NextTrace Project
Leo

**Comment by famuserpro** [comment]
请问能否保留？这个模式简洁明了，比另外2个看起来更加养眼。谢谢

**Comment by sjlleo** [comment]
> 请问能否保留？这个模式简洁明了，比另外2个看起来更加养眼。谢谢

抱歉，Classic 在 0.2.0 版本就已经被废弃了，但是考虑到还有相当多的用户在使用这个模式，所以我们预留了充分的窗口期，并且持续兼容至今。

考虑到这种情况，您可以继续使用 v1.0.8 版本，这是一个很成熟的版本，目前我们测试下来没有遇到严重的 Bug，可以长期使用。您可以看到哪怕是 0.1.14 版本我们依旧提供了 API 的长期支持，虽然无法体验很多新特性，但是不影响正常的使用。

不过，为了您能够体验完整的特性，我还是建议您尽快切换到 table 模式，它同样简洁明了，同时支持实时的追踪数据显示。
