### ISSUE TITLE
能不能让解析速度快一点, 每一跳都要解析好几秒, 一整个路由解析下来二三十秒.........

### ISSUE THREAD

**Issue by wutongskype** [sjlleo/nexttrace#78]
能不能让解析速度快一点, 每一跳都要解析好几秒, 一整个路由解析下来二三十秒.........
对比一下, 一个15~20跳的路由测试, 用Best Trace大概10秒左右, nexttrace测试下来时间多大概一倍还多.....

**Comment by tsosunchia** [comment]
您使用的是nexttrace哪个版本，网络是什么环境？

**Comment by wutongskype** [comment]
> 您使用的是nexttrace哪个版本，网络是什么环境？
最新版的 NextTrace v1.1.1 2023-02-16T13:31:42Z 50b3e44
系统是d11 网络北方联通
刚仔细看了下时间, 同一个网站, 用besttrace测下来11秒 nexttrace测下来20秒左右
即使加上 -q 1 以后也还要13~15秒.. 
而 besttrace加上-q 1 只需要8秒

**Comment by sjlleo** [comment]
Hi wutongskype,

我们的API服务器位于新加坡阿里云，但是因为套了Cloudflare以防止DDoS攻击，所以国内过去延迟响应都不是很好，
由于此项目是非盈利性质的开源项目，我们目前没有更多资金以购买更好的高防且专为国内三网优化的服务器。

如果您追求快速、高效、精准，您可能应该首先考虑诸如 BestTrace 等商业产品，他们的服务器通常在国内，
可以为您提供更快的测试。作为一款开源软件，体验不如商业软件并不意外，这应该是您使用前应该知悉的。

感谢您的反馈，但是很遗憾的是我们目前无论是从时间精力还是财力上都没有办法改善这个问题，
如果您对这方面敏感，我们还是建议您还是使用 BestTrace 作为首选项，NextTrace 可能还是更适合热爱开源社区又或者是对路由跟踪的隐私和安全有较高要求的朋友来使用。

Leo

**Comment by wutongskype** [comment]
> Hi wutongskype,
> 
> 我们的API服务器位于新加坡阿里云，但是因为套了Cloudflare以防止DDoS攻击，所以国内过去延迟响应都不是很好， 由于此项目是非盈利性质的开源项目，我们目前没有更多资金以购买更好的高防且专为国内三网优化的服务器。
> 
> 如果您追求快速、高效、精准，您可能应该首先考虑诸如 BestTrace 等商业产品，他们的服务器通常在国内， 可以为您提供更快的测试。作为一款开源软件，体验不如商业软件并不意外，这应该是您使用前应该知悉的。
> 
> 感谢您的反馈，但是很遗憾的是我们目前无论是从时间精力还是财力上都没有办法改善这个问题， 如果您对这方面敏感，我们还是建议您还是使用 BestTrace 作为首选项，NextTrace 可能还是更适合热爱开源社区又或者是对路由跟踪的隐私和安全有较高要求的朋友来使用。
> 
> Leo

是中间联网查ip归属地那块耗时是吗？
可否使用本地库或者关掉？

**Comment by tsosunchia** [comment]
> > Hi wutongskype,
> > 我们的API服务器位于新加坡阿里云，但是因为套了Cloudflare以防止DDoS攻击，所以国内过去延迟响应都不是很好， 由于此项目是非盈利性质的开源项目，我们目前没有更多资金以购买更好的高防且专为国内三网优化的服务器。
> > 如果您追求快速、高效、精准，您可能应该首先考虑诸如 BestTrace 等商业产品，他们的服务器通常在国内， 可以为您提供更快的测试。作为一款开源软件，体验不如商业软件并不意外，这应该是您使用前应该知悉的。
> > 感谢您的反馈，但是很遗憾的是我们目前无论是从时间精力还是财力上都没有办法改善这个问题， 如果您对这方面敏感，我们还是建议您还是使用 BestTrace 作为首选项，NextTrace 可能还是更适合热爱开源社区又或者是对路由跟踪的隐私和安全有较高要求的朋友来使用。
> > Leo
> 
> 是中间联网查ip归属地那块耗时是吗？ 可否使用本地库或者关掉？

在大部分情况下，我们的API速度还是可以接受的（包括您使用的北方联通，我们这里测试速度不存在您提到的情况），
对于您提到的“本地库”支持，我们在v0.2.2及之后的几个版本短暂支持了ip2region这一离线库，您可以使用那几个版本的release。

**Comment by famuserpro** [comment]
我也北方联通 但是有软路由 根本没这个问题 你自己慢 怪谁 要快为什么不用besttrace

**Comment by wutongskype** [comment]
> > > Hi wutongskype,
> > > 我们的API服务器位于新加坡阿里云，但是因为套了Cloudflare以防止DDoS攻击，所以国内过去延迟响应都不是很好， 由于此项目是非盈利性质的开源项目，我们目前没有更多资金以购买更好的高防且专为国内三网优化的服务器。
> > > 如果您追求快速、高效、精准，您可能应该首先考虑诸如 BestTrace 等商业产品，他们的服务器通常在国内， 可以为您提供更快的测试。作为一款开源软件，体验不如商业软件并不意外，这应该是您使用前应该知悉的。
> > > 感谢您的反馈，但是很遗憾的是我们目前无论是从时间精力还是财力上都没有办法改善这个问题， 如果您对这方面敏感，我们还是建议您还是使用 BestTrace 作为首选项，NextTrace 可能还是更适合热爱开源社区又或者是对路由跟踪的隐私和安全有较高要求的朋友来使用。
> > > Leo
> > 
> > 
> > 是中间联网查ip归属地那块耗时是吗？ 可否使用本地库或者关掉？
> 
> 在大部分情况下，我们的API速度还是可以接受的（包括您使用的北方联通，我们这里测试速度不存在您提到的情况）， 对于您提到的“本地库”支持，我们在`v0.2.2`及之后的几个版本短暂支持了ip2region这一离线库，您可以使用那几个版本的release。 此外您当然也可以使用其他第三方API，NextTrace还支持`IP.SB, IPInfo, IPInsight,IPAPI.com`等API，您可以使用`-d`参数调用它们。 PS：目前由于精力所限，无任何重新添加此离线库的打算，特此说明。

@tsosunchia
感觉和api关系不大... 可能是每一跳间隔时间有点长, 具体的我也没法搞清楚
我又进行了一些测试, 上面是用的家里的测境外阿里云hk,
这次用境外的阿里云hk的服务器测国内的家里的ip, 时间也差不多
试过换api, 我这家里ping IPInfo 也就40ms左右, 换了它也没多大改善.

@famuserpro besttrace一般般了, 同样环境, 用traceroute可以6~7秒测完, 我只是提点建议, 能改善点更好, 不能改就这样了也无所谓, 备胎工具多了去了

**Comment by tsosunchia** [comment]
> @tsosunchia 感觉和api关系不大... 可能是每一跳间隔时间有点长, 具体的我也没法搞清楚 我又进行了一些测试, 上面是用的家里的测境外阿里云hk, 这次用境外的阿里云hk的服务器测国内的家里的ip, 时间也差不多 试过换api, 我这家里ping IPInfo 也就40ms左右, 换了它也没多大改善.

恕我无法认同，我们这边进行过benchmark，无论是境内移动联通还是境外主机，nexttrace的速度是要比besttrace快不少的，我认为问题应该出在您的本地环境。

**Comment by isyekong** [comment]
想要快并不显示 GEO 信息，可以直接使用 MTR。
发送间隔默认应该是 100ms，此项目是非盈利性质的开源项目，与其他成熟且封闭的商业产品有差距是很正常的事情。
目前已经是经过多次迭代优化后的版本，如果您有更好的代码实现，可以与开发组分享

**Comment by sjlleo** [comment]
又是不看参数的...

想要快如 mtr 很简单，降低发送等待间隔即可，但是这样发出来的包对于部分路由器会导致延迟不准确

1. 我们明确给高级用户提供了 --send-time 参数，它意味着每个包的发送冷却时间，默认是100ms，您要快，这个值可以为0
2. 我们明确为高级用户提供了--ttl-time 参数，它意味着每组ttl的发送冷却时间，默认是500ms，您要快，这个值可以设置为1

您想要快这样写就可以：
```
nexttrace -z 0 -i 1 8.8.8.8
```

至于为什么不默认这么设置，因为我们对延迟的准确度远高于速度。

**Comment by xsgteamx** [comment]
> 能不能让解析速度快一点, 每一跳都要解析好几秒, 一整个路由解析下来二三十秒......... 对比一下, 一个15~20跳的路由测试, 用Best Trace大概10秒左右, nexttrace测试下来时间多大概一倍还多.....

可以加速，打钱就可以
