### ISSUE TITLE
Is TCP tracing available in Windows binary?

### ISSUE THREAD

**Issue by Nirvanatin** [sjlleo/nexttrace#87]
Can Windows binaries be used for TCP tracing?
```
nexttrace_windows_amd64.exe --tcp --port 443 50.29.*.*
NextTrace v1.1.3 2023-03-03T07:51:20Z ead7ebb
NextTrace 基于 Windows 的路由跟踪还在早期开发阶段，目前还存在诸多问题，TCP/UDP SYN 包请求可能不能正常运行
[NextTrace API] prefered API IP - 104.26.*.* - 12.92ms
IP Geo Data Provider: LeoMoeAPI
traceroute to 50.29.*.*, 30 hops max, 32 byte packets
2023/03/11 02:38:28 listen ip4:tcp 192.168.1.102: bind: An invalid argument was supplied.
```

**Comment by sjlleo** [comment]
> Can Windows binaries be used for TCP tracing?
> 
> ```
> nexttrace_windows_amd64.exe --tcp --port 443 50.29.*.*
> NextTrace v1.1.3 2023-03-03T07:51:20Z ead7ebb
> NextTrace 基于 Windows 的路由跟踪还在早期开发阶段，目前还存在诸多问题，TCP/UDP SYN 包请求可能不能正常运行
> [NextTrace API] prefered API IP - 104.26.*.* - 12.92ms
> IP Geo Data Provider: LeoMoeAPI
> traceroute to 50.29.*.*, 30 hops max, 32 byte packets
> 2023/03/11 02:38:28 listen ip4:tcp 192.168.1.102: bind: An invalid argument was supplied.
> ```

Dear Nirvanatin,

Thank you for your message regarding the NextTrace Windows branch. I regret to inform you that we currently do not have any plans to support additional functionalities for the Windows branch in the near future. However, we appreciate your interest and would encourage you to continue following our progress and updates.

Please let us know if you have any further questions or concerns.

Best regards,
Leo
