### ISSUE TITLE
项目这是停更了吗

### ISSUE THREAD

**Issue by famuserpro** [sjlleo/nexttrace#88]
最近几个反馈没有任何回复  ip 位置都没校过来

**Comment by tsosunchia** [comment]
没停更

**Comment by famuserpro** [comment]
> 没停更

我发了一些ip错误文件到作者邮箱 但是没有回应

**Comment by isyekong** [comment]
> 

建议您提交 issue

**Comment by tsosunchia** [comment]
> > 没停更
> 
> 我发了一些ip错误文件到作者邮箱 但是没有回应

不要发邮箱，纠正IP位置请发到这个issue里 #41

**Comment by famuserpro** [comment]
ip涉及隐私 我不是很想发在这里 你们有其他邮箱吗 以前半天内就会更新

**Comment by tsosunchia** [comment]
> ip涉及隐私 我不是很想发在这里 你们有其他邮箱吗 以前半天内就会更新

对于BUG修复和IP信息纠正，我们不提供任何即时通讯软件或电子邮件的联系方法。

**Comment by famuserpro** [comment]
> 对于BUG修复和IP信息纠正，我们不提供任何即时通讯软件或电子邮件的联系方法。 之前你发到OWNER邮箱，这种做法是不推荐的。

好吧 所以那个邮箱是废弃了吗 后面我就发到 issue 上来吧

**Comment by tsosunchia** [comment]
> > 对于BUG修复和IP信息纠正，我们不提供任何即时通讯软件或电子邮件的联系方法。 之前你发到OWNER邮箱，这种做法是不推荐的。
> 
> 好吧 所以那个邮箱是废弃了吗 后面我就发到 issue 上来吧

并不是那个邮箱废弃了，只是那个邮箱是个人邮箱，不是解决您提出的这些问题的地方。
