### ISSUE TITLE
LeoMoeAPI 服务器变更

### ISSUE THREAD

**Issue by sjlleo** [sjlleo/nexttrace#92]
由于众所周知的原因，在2023年3月31日，由于经费不足，组员带着服务器的 CPU 和内存跑路了，我们的服务器无法启动。为了保证能够向所有用户继续提供服务，我们紧急从图吧捡了一台 CPU 为 AMD FX8320，并采用红星高端电源，显卡使用旗舰竞技级 Nvidia GT 705，并安装 Windows 98 系统的 PC，成功点亮！

如果您遇到任何使用上的问题或困惑，请立即与我们联系。在力所能及的范围内，我们将尽力而为向您提供最优质的服♂务。

**2023/4/1**
Leo
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

愚人节快乐！

**Comment by nickfox-taterli** [comment]
起码跑个NT3.51吧...
