### ISSUE TITLE
支持探测过程及结果支持上报到prometheus

### ISSUE THREAD

**Issue by nondevops** [sjlleo/nexttrace#96]
**Is your feature request related to a problem? Please describe.**
全球用户到服务器的网络链路较长，加上用户存在各种各样的网络环境，对网络监控是运维角色及整改IT基础设施稳定性的重要监控对象。

**Describe the solution you'd like**
将探测结果上报到支持prometheus格式的时序库进行存储，让监控通过阀值等手段进行告警。
例如,http://xxxxxx:9453/metric，9453代表 nexttrace服务的端口

**Describe alternatives you've considered**

**Additional context**

**Comment by nondevops** [comment]
> 

@tsosunchia ping blackbox 没有跟踪路由的功能，无法做到可视化，您的项目已经具备基础条件了，只要包装入口形成服务，我相信它能成为在网络监控领域的重要利器。

**Comment by sjlleo** [comment]
Hi nondevops,

后续会考虑支持，NextTrace 有计划增加 metrics 包以对外提供信息。

Leo

**Comment by sjlleo** [comment]
如无其他问题，本 issue 将被关闭，如需要对该功能有更多补充，请新提 issue。
