### ISSUE TITLE
MapTrace 增加一个本地公网出口 IP 地址

### ISSUE THREAD

**Issue by kong62** [sjlleo/nexttrace#97]
**Is your feature request related to a problem? Please describe.**
MapTrace 增加一个本地公网出口 IP 地址，不然太突兀了。

**Additional context**
```https://api.leo.moe/tracemap/8d4dbaa7-86a3-5bc1-92ad-ce88511c29f0.html```
![image](https://user-images.githubusercontent.com/10241723/232447786-515b2cf8-ffba-41c1-8294-5005a1b4de40.png)

**Comment by tsosunchia** [comment]
麻烦您将issue发送至[traceMap项目](https://github.com/tsosunchia/traceMap)
#89 

> 对于本项目集成的其他API 的信息纠正以及NextTrace MapTrace的相关问题，请发至相应的地方。

----------------------

> For information correction of other APIs integrated in this project and related issues of NextTrace MapTrace, please send them to the corresponding place.
