### ISSUE TITLE
是否可以集成mtr的丢包率功能

### ISSUE THREAD

**Issue by aliuzzz** [sjlleo/nexttrace#99]
https://github.com/traviscross/mtr
mtr里的丢包率，支持设置数据包大小，如果能集成进来将是极好的，可以直接替代mtr了

**Comment by tsosunchia** [comment]
类似mtr的功能我们已经在另外一个项目中实现，但是由于精力所限那个项目还没有完备到可以开源的地步。
感谢您的关注。

**Comment by tsosunchia** [comment]
[OPENTRACE](https://github.com/Archeb/opentrace)和[NEXTTRACEWEBAPI](https://github.com/tsosunchia/nexttracewebapi)均已很好的实现了你的需求，可以看一下。
